/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Comment2 from './Comment2';

/**
 * The CommentGetEmbedded2Embedded model module.
 * @module model/CommentGetEmbedded2Embedded
 * @version 1.1.1
 */
class CommentGetEmbedded2Embedded {
    /**
     * Constructs a new <code>CommentGetEmbedded2Embedded</code>.
     * @alias module:model/CommentGetEmbedded2Embedded
     */
    constructor() { 
        
        CommentGetEmbedded2Embedded.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CommentGetEmbedded2Embedded</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CommentGetEmbedded2Embedded} obj Optional instance to populate.
     * @return {module:model/CommentGetEmbedded2Embedded} The populated <code>CommentGetEmbedded2Embedded</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommentGetEmbedded2Embedded();

            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], [Comment2]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Comment2>} comments
 */
CommentGetEmbedded2Embedded.prototype['comments'] = undefined;






export default CommentGetEmbedded2Embedded;

