/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.3.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DegreeGetEmbedded from './DegreeGetEmbedded';
import DegreeGetEmbeddedEmbedded from './DegreeGetEmbeddedEmbedded';
import GetResponse from './GetResponse';
import PaginationPage from './PaginationPage';

/**
 * The DegreeGetResponse model module.
 * @module model/DegreeGetResponse
 * @version 1.3.10
 */
class DegreeGetResponse {
    /**
     * Constructs a new <code>DegreeGetResponse</code>.
     * @alias module:model/DegreeGetResponse
     * @implements module:model/GetResponse
     * @implements module:model/DegreeGetEmbedded
     */
    constructor() { 
        GetResponse.initialize(this);DegreeGetEmbedded.initialize(this);
        DegreeGetResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DegreeGetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DegreeGetResponse} obj Optional instance to populate.
     * @return {module:model/DegreeGetResponse} The populated <code>DegreeGetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DegreeGetResponse();
            GetResponse.constructFromObject(data, obj);
            DegreeGetEmbedded.constructFromObject(data, obj);

            if (data.hasOwnProperty('page')) {
                obj['page'] = PaginationPage.constructFromObject(data['page']);
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = DegreeGetEmbeddedEmbedded.constructFromObject(data['_embedded']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PaginationPage} page
 */
DegreeGetResponse.prototype['page'] = undefined;

/**
 * @member {module:model/DegreeGetEmbeddedEmbedded} _embedded
 */
DegreeGetResponse.prototype['_embedded'] = undefined;


// Implement GetResponse interface:
/**
 * @member {module:model/PaginationPage} page
 */
GetResponse.prototype['page'] = undefined;
// Implement DegreeGetEmbedded interface:
/**
 * @member {module:model/DegreeGetEmbeddedEmbedded} _embedded
 */
DegreeGetEmbedded.prototype['_embedded'] = undefined;




export default DegreeGetResponse;

