/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject model module.
 * @module model/InlineObject
 * @version 1.0.4
 */
class InlineObject {
    /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:model/InlineObject
     * @param username {String} Nombre del nuevo usuario
     * @param password {String} Contraseña del nuevo usuario
     * @param email {String} Email del nuevo usuario
     * @param description {String} Descripción para el nuevo usuario
     * @param universityId {Number} Universidad del usuario
     * @param photo {File} Foto del usuario
     */
    constructor(username, password, email, description, universityId, photo) { 
        
        InlineObject.initialize(this, username, password, email, description, universityId, photo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password, email, description, universityId, photo) { 
        obj['username'] = username;
        obj['password'] = password;
        obj['email'] = email;
        obj['description'] = description;
        obj['university_id'] = universityId;
        obj['photo'] = photo;
    }

    /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject} obj Optional instance to populate.
     * @return {module:model/InlineObject} The populated <code>InlineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('university_id')) {
                obj['university_id'] = ApiClient.convertToType(data['university_id'], 'Number');
            }
            if (data.hasOwnProperty('photo')) {
                obj['photo'] = ApiClient.convertToType(data['photo'], File);
            }
        }
        return obj;
    }


}

/**
 * Nombre del nuevo usuario
 * @member {String} username
 */
InlineObject.prototype['username'] = undefined;

/**
 * Contraseña del nuevo usuario
 * @member {String} password
 */
InlineObject.prototype['password'] = undefined;

/**
 * Email del nuevo usuario
 * @member {String} email
 */
InlineObject.prototype['email'] = undefined;

/**
 * Descripción para el nuevo usuario
 * @member {String} description
 */
InlineObject.prototype['description'] = undefined;

/**
 * Universidad del usuario
 * @member {Number} university_id
 */
InlineObject.prototype['university_id'] = undefined;

/**
 * Foto del usuario
 * @member {File} photo
 */
InlineObject.prototype['photo'] = undefined;






export default InlineObject;

