/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.3.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetResponse2 from './GetResponse2';
import PaginationPage2 from './PaginationPage2';
import ReproductionListGetEmbedded2 from './ReproductionListGetEmbedded2';
import ReproductionListGetEmbedded2Embedded from './ReproductionListGetEmbedded2Embedded';

/**
 * The ReproductionListGetResponse2 model module.
 * @module model/ReproductionListGetResponse2
 * @version 1.3.12
 */
class ReproductionListGetResponse2 {
    /**
     * Constructs a new <code>ReproductionListGetResponse2</code>.
     * @alias module:model/ReproductionListGetResponse2
     * @implements module:model/GetResponse2
     * @implements module:model/ReproductionListGetEmbedded2
     */
    constructor() { 
        GetResponse2.initialize(this);ReproductionListGetEmbedded2.initialize(this);
        ReproductionListGetResponse2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReproductionListGetResponse2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReproductionListGetResponse2} obj Optional instance to populate.
     * @return {module:model/ReproductionListGetResponse2} The populated <code>ReproductionListGetResponse2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReproductionListGetResponse2();
            GetResponse2.constructFromObject(data, obj);
            ReproductionListGetEmbedded2.constructFromObject(data, obj);

            if (data.hasOwnProperty('page')) {
                obj['page'] = PaginationPage2.constructFromObject(data['page']);
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ReproductionListGetEmbedded2Embedded.constructFromObject(data['_embedded']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PaginationPage2} page
 */
ReproductionListGetResponse2.prototype['page'] = undefined;

/**
 * @member {module:model/ReproductionListGetEmbedded2Embedded} _embedded
 */
ReproductionListGetResponse2.prototype['_embedded'] = undefined;


// Implement GetResponse2 interface:
/**
 * @member {module:model/PaginationPage2} page
 */
GetResponse2.prototype['page'] = undefined;
// Implement ReproductionListGetEmbedded2 interface:
/**
 * @member {module:model/ReproductionListGetEmbedded2Embedded} _embedded
 */
ReproductionListGetEmbedded2.prototype['_embedded'] = undefined;




export default ReproductionListGetResponse2;

