/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SelfLinkLinks from './SelfLinkLinks';

/**
 * The SelfLink model module.
 * @module model/SelfLink
 * @version 1.0.7
 */
class SelfLink {
    /**
     * Constructs a new <code>SelfLink</code>.
     * @alias module:model/SelfLink
     */
    constructor() { 
        
        SelfLink.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SelfLink</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SelfLink} obj Optional instance to populate.
     * @return {module:model/SelfLink} The populated <code>SelfLink</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SelfLink();

            if (data.hasOwnProperty('_links')) {
                obj['_links'] = SelfLinkLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SelfLinkLinks} _links
 */
SelfLink.prototype['_links'] = undefined;






export default SelfLink;

