/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HalLink from './HalLink';

/**
 * The SelfLinkLinks model module.
 * @module model/SelfLinkLinks
 * @version 1.0.6
 */
class SelfLinkLinks {
    /**
     * Constructs a new <code>SelfLinkLinks</code>.
     * @alias module:model/SelfLinkLinks
     */
    constructor() { 
        
        SelfLinkLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SelfLinkLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SelfLinkLinks} obj Optional instance to populate.
     * @return {module:model/SelfLinkLinks} The populated <code>SelfLinkLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SelfLinkLinks();

            if (data.hasOwnProperty('self')) {
                obj['self'] = HalLink.constructFromObject(data['self']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/HalLink} self
 */
SelfLinkLinks.prototype['self'] = undefined;






export default SelfLinkLinks;

