/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import University from './University';
import UniversityLinks from './UniversityLinks';
import UniversityLinksLinks from './UniversityLinksLinks';

/**
 * The UniversityWithLinks model module.
 * @module model/UniversityWithLinks
 * @version 1.0.6
 */
class UniversityWithLinks {
    /**
     * Constructs a new <code>UniversityWithLinks</code>.
     * @alias module:model/UniversityWithLinks
     * @extends module:model/University
     * @implements module:model/University
     * @implements module:model/UniversityLinks
     * @param name {String} 
     */
    constructor(name) { 
        University.initialize(this, name);UniversityLinks.initialize(this);
        UniversityWithLinks.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
    }

    /**
     * Constructs a <code>UniversityWithLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityWithLinks} obj Optional instance to populate.
     * @return {module:model/UniversityWithLinks} The populated <code>UniversityWithLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityWithLinks();
            University.constructFromObject(data, obj);
            University.constructFromObject(data, obj);
            UniversityLinks.constructFromObject(data, obj);

            if (data.hasOwnProperty('_links')) {
                obj['_links'] = UniversityLinksLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UniversityLinksLinks} _links
 */
UniversityWithLinks.prototype['_links'] = undefined;


// Implement University interface:
/**
 * @member {Number} id
 */
University.prototype['id'] = undefined;
/**
 * @member {String} name
 */
University.prototype['name'] = undefined;
// Implement UniversityLinks interface:
/**
 * @member {module:model/UniversityLinksLinks} _links
 */
UniversityLinks.prototype['_links'] = undefined;




export default UniversityWithLinks;

