/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HalLink from './HalLink';

/**
 * The UniversityLinks model module.
 * @module model/UniversityLinks
 * @version 1.0.0
 */
class UniversityLinks {
    /**
     * Constructs a new <code>UniversityLinks</code>.
     * @alias module:model/UniversityLinks
     */
    constructor() { 
        
        UniversityLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UniversityLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityLinks} obj Optional instance to populate.
     * @return {module:model/UniversityLinks} The populated <code>UniversityLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityLinks();

            if (data.hasOwnProperty('self')) {
                obj['self'] = HalLink.constructFromObject(data['self']);
            }
            if (data.hasOwnProperty('university')) {
                obj['university'] = HalLink.constructFromObject(data['university']);
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = HalLink.constructFromObject(data['users']);
            }
            if (data.hasOwnProperty('subjects')) {
                obj['subjects'] = HalLink.constructFromObject(data['subjects']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/HalLink} self
 */
UniversityLinks.prototype['self'] = undefined;

/**
 * @member {module:model/HalLink} university
 */
UniversityLinks.prototype['university'] = undefined;

/**
 * @member {module:model/HalLink} users
 */
UniversityLinks.prototype['users'] = undefined;

/**
 * @member {module:model/HalLink} subjects
 */
UniversityLinks.prototype['subjects'] = undefined;






export default UniversityLinks;

