/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UniversityGetEmbeddedTest from './UniversityGetEmbeddedTest';
import UniversityGetEmbeddedTestEmbedded from './UniversityGetEmbeddedTestEmbedded';

/**
 * The UniversityFindByNameStartsWith model module.
 * @module model/UniversityFindByNameStartsWith
 * @version 1.0.6
 */
class UniversityFindByNameStartsWith {
    /**
     * Constructs a new <code>UniversityFindByNameStartsWith</code>.
     * @alias module:model/UniversityFindByNameStartsWith
     * @implements module:model/UniversityGetEmbeddedTest
     */
    constructor() { 
        UniversityGetEmbeddedTest.initialize(this);
        UniversityFindByNameStartsWith.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UniversityFindByNameStartsWith</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityFindByNameStartsWith} obj Optional instance to populate.
     * @return {module:model/UniversityFindByNameStartsWith} The populated <code>UniversityFindByNameStartsWith</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityFindByNameStartsWith();
            UniversityGetEmbeddedTest.constructFromObject(data, obj);

            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = UniversityGetEmbeddedTestEmbedded.constructFromObject(data['_embedded']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UniversityGetEmbeddedTestEmbedded} _embedded
 */
UniversityFindByNameStartsWith.prototype['_embedded'] = undefined;


// Implement UniversityGetEmbeddedTest interface:
/**
 * @member {module:model/UniversityGetEmbeddedTestEmbedded} _embedded
 */
UniversityGetEmbeddedTest.prototype['_embedded'] = undefined;




export default UniversityFindByNameStartsWith;

