/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UniversityLinksLinks from './UniversityLinksLinks';

/**
 * The UniversityLinks model module.
 * @module model/UniversityLinks
 * @version 1.0.7
 */
class UniversityLinks {
    /**
     * Constructs a new <code>UniversityLinks</code>.
     * @alias module:model/UniversityLinks
     */
    constructor() { 
        
        UniversityLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UniversityLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityLinks} obj Optional instance to populate.
     * @return {module:model/UniversityLinks} The populated <code>UniversityLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityLinks();

            if (data.hasOwnProperty('_links')) {
                obj['_links'] = UniversityLinksLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UniversityLinksLinks} _links
 */
UniversityLinks.prototype['_links'] = undefined;






export default UniversityLinks;

