/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserLinksLinks from './UserLinksLinks';

/**
 * The UserLinks model module.
 * @module model/UserLinks
 * @version 1.0.7
 */
class UserLinks {
    /**
     * Constructs a new <code>UserLinks</code>.
     * @alias module:model/UserLinks
     */
    constructor() { 
        
        UserLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserLinks} obj Optional instance to populate.
     * @return {module:model/UserLinks} The populated <code>UserLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLinks();

            if (data.hasOwnProperty('_links')) {
                obj['_links'] = UserLinksLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserLinksLinks} _links
 */
UserLinks.prototype['_links'] = undefined;






export default UserLinks;

