/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User2 from './User2';

/**
 * The UserGetEmbedded2Embedded model module.
 * @module model/UserGetEmbedded2Embedded
 * @version 1.3.0
 */
class UserGetEmbedded2Embedded {
    /**
     * Constructs a new <code>UserGetEmbedded2Embedded</code>.
     * @alias module:model/UserGetEmbedded2Embedded
     */
    constructor() { 
        
        UserGetEmbedded2Embedded.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserGetEmbedded2Embedded</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserGetEmbedded2Embedded} obj Optional instance to populate.
     * @return {module:model/UserGetEmbedded2Embedded} The populated <code>UserGetEmbedded2Embedded</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserGetEmbedded2Embedded();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [User2]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/User2>} users
 */
UserGetEmbedded2Embedded.prototype['users'] = undefined;






export default UserGetEmbedded2Embedded;

