/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerUnicast);
  }
}(this, function(expect, SwaggerUnicast) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerUnicast.DegreeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DegreeApi', function() {
    describe('addDegree', function() {
      it('should call addDegree successfully', function(done) {
        //uncomment below and update the code to test addDegree
        //instance.addDegree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findDegreesByName', function() {
      it('should call findDegreesByName successfully', function(done) {
        //uncomment below and update the code to test findDegreesByName
        //instance.findDegreesByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findDegreesContainingName', function() {
      it('should call findDegreesContainingName successfully', function(done) {
        //uncomment below and update the code to test findDegreesContainingName
        //instance.findDegreesContainingName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findDegreesStartsWith', function() {
      it('should call findDegreesStartsWith successfully', function(done) {
        //uncomment below and update the code to test findDegreesStartsWith
        //instance.findDegreesStartsWith(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDegrees', function() {
      it('should call getDegrees successfully', function(done) {
        //uncomment below and update the code to test getDegrees
        //instance.getDegrees(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUniversitiesFromDegree', function() {
      it('should call getUniversitiesFromDegree successfully', function(done) {
        //uncomment below and update the code to test getUniversitiesFromDegree
        //instance.getUniversitiesFromDegree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putDegreeUniversity', function() {
      it('should call putDegreeUniversity successfully', function(done) {
        //uncomment below and update the code to test putDegreeUniversity
        //instance.putDegreeUniversity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDegree', function() {
      it('should call updateDegree successfully', function(done) {
        //uncomment below and update the code to test updateDegree
        //instance.updateDegree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
