/**
 * Swagger Unicast
 * Documento de la API de Unicast
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerUnicast);
  }
}(this, function(expect, SwaggerUnicast) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerUnicast.VideoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VideoApi', function() {
    describe('addVideo', function() {
      it('should call addVideo successfully', function(done) {
        //uncomment below and update the code to test addVideo
        //instance.addVideo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findVideosContainingTitle', function() {
      it('should call findVideosContainingTitle successfully', function(done) {
        //uncomment below and update the code to test findVideosContainingTitle
        //instance.findVideosContainingTitle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findVideosStartsWithTitle', function() {
      it('should call findVideosStartsWithTitle successfully', function(done) {
        //uncomment below and update the code to test findVideosStartsWithTitle
        //instance.findVideosStartsWithTitle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideo', function() {
      it('should call getVideo successfully', function(done) {
        //uncomment below and update the code to test getVideo
        //instance.getVideo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideoSubject', function() {
      it('should call getVideoSubject successfully', function(done) {
        //uncomment below and update the code to test getVideoSubject
        //instance.getVideoSubject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideoUploader', function() {
      it('should call getVideoUploader successfully', function(done) {
        //uncomment below and update the code to test getVideoUploader
        //instance.getVideoUploader(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideos', function() {
      it('should call getVideos successfully', function(done) {
        //uncomment below and update the code to test getVideos
        //instance.getVideos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideosFromSubject', function() {
      it('should call getVideosFromSubject successfully', function(done) {
        //uncomment below and update the code to test getVideosFromSubject
        //instance.getVideosFromSubject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideosFromUploader', function() {
      it('should call getVideosFromUploader successfully', function(done) {
        //uncomment below and update the code to test getVideosFromUploader
        //instance.getVideosFromUploader(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVideosOfUserSubjects', function() {
      it('should call getVideosOfUserSubjects successfully', function(done) {
        //uncomment below and update the code to test getVideosOfUserSubjects
        //instance.getVideosOfUserSubjects(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
